export interface PerfilEstudiante {
  id: string;
  idUsuario: string;
  fechaNacimiento: string;
  edad: number;
  sexo: string;
  municipioNacimiento: string;
  departamentoNacimiento: string;
  paisNacimiento: string;
  religion: string;
  direccionActual: string;
  barrioVeredaActual: string;
  ciudadActual: string;
  departamentoActual: string;
  paisActual: string;
  fileFoto: string;
  fileDoc: string;
  fileDiagnostico: string | null;
  limitaciones: string | null;
  otrasLimitaciones: string | null;
  capacidades: string | null;
  ciPuntaje: number | null;
  problemasalud: string | null;
  eps: string;
  ips: string;
  rh: string;
  observaciones: string | null;
  padreApellido1: string;
  padreApellido2: string;
  padreNombre: string;
  padreCedula: string;
  padreContacto1: string;
  padreContacto2: string | null;
  padreFile: string;
  madreApellido1: string;
  madreApellido2: string;
  madreNombre: string;
  madreCedula: string;
  madreContacto1: string;
  madreContacto2: string | null;
  madreFile: string;
  acudienteApellido1: string;
  acudienteApellido2: string;
  acudienteNombre: string;
  acudienteCedula: string;
  acudienteContacto1: string;
  acudienteContacto2: string | null;
  acudienteFile: string;
  ref1Nombres: string;
  ref1Apellidos: string;
  ref1Tel: string;
  ref2Nombres: string;
  ref2Apellidos: string;
  ref2Tel: string;
  ref3Nombres: string;
  ref3Apellidos: string;
  ref3Tel: string;
  ref4Nombres: string;
  ref4Apellidos: string;
  ref4Tel: string;
  ref5Nombres: string;
  ref5Apellidos: string;
  ref5Tel: string;
  ref6Nombres: string;
  ref6Apellidos: string;
  ref6Tel: string;
  // Usuario JOIN fields
  usuarioNombres: string;
  usuarioApellido1: string;
  usuarioApellido2: string | null;
  usuarioContacto1: string | null;
  usuarioContacto2: string | null;
  usuarioEmail: string | null;
  usuarioIdRol: string | null;
  usuarioEstado: string;
  usuarioIdTipoDocumento: string | null;
  usuarioNoDocumento: string | null;
  usuarioFechaExpedicionDocumento: string | null;
}
